package com.buaa.act.sdp.common;

/**
 * Created by yang on 2016/11/24.
 */
public class Constant {
    public static final String [] TECH = {
            ".net",
            ".net 2.0",
            ".net 3.0",
            ".net 3.5",
            ".net 4.0",
            ".net system.addins",
            "actionscript",
            "active directory",
            "activity diagrams (tcuml)",
            "ado.net",
            "ai",
            "ajax",
            "android",
            "android 2.0",
            "android 2.1",
            "android 2.2",
            "angular.js",
            "ant",
            "apache derby",
            "apex",
            "api",
            "applet",
            "asp.net",
            "asp.net ajax",
            "asp.net web parts",
            "aws",
            "backbone.js",
            "beanstalk",
            "biztalk",
            "blackberry sdk",
            "bootstrap",
            "box",
            "brivo labs",
            "c",
            "c#",
            "c++",
            "castor",
            "chatter",
            "cisco",
            "clickonce",
            "cloud foundry",
            "cloudfactor",
            "cobol",
            "coffeescript",
            "cognitive",
            "com",
            "com+",
            "commerce server 2009",
            "css",
            "custom tag",
            "data science",
            "databasedotcom",
            "docker",
            "docusign",
            "dojo",
            "drools",
            "ec2",
            "eclipse plugin",
            "ejb",
            "ejb 3",
            "elasticsearch",
            "express",
            "facebook",
            "financialforce",
            "flash",
            "flex",
            "force.com",
            "force.com sites",
            "fortran",
            "gaming",
            "go",
            "google",
            "google api",
            "google app engine",
            "gradle",
            "grommet",
            "groovy",
            "heroku",
            "hibernate",
            "hp haven",
            "hpe haven ondemand",
            "html",
            "html5",
            "http",
            "ibatis/mybatis",
            "ibm aix",
            "ibm bluemix",
            "ibm cognitive",
            "ibm cognos",
            "ibm content manager",
            "ibm db2",
            "ibm lotus domino",
            "ibm lotus notes",
            "ibm pl/1",
            "ibm rational application developer",
            "ibm rational data architect",
            "ibm rational data studio",
            "ibm rational software architect",
            "ibm rational team concert",
            "ibm rexx",
            "ibm watson",
            "ibm websphere application server",
            "ibm websphere datapower",
            "ibm websphere datastage",
            "ibm websphere message broker",
            "ibm websphere mq",
            "ibm websphere portal",
            "iis",
            "illustrator",
            "ionic",
            "ios",
            "ios 4.0",
            "ios 5.0",
            "ios 6.0",
            "ios 8.0",
            "j2ee",
            "j2me",
            "jabber",
            "java",
            "java application",
            "javabean",
            "javascript",
            "jboss seam",
            "jdbc",
            "jface",
            "jms",
            "jpa",
            "jquery",
            "jquery mobile",
            "jsf",
            "json",
            "jsp",
            "junit",
            "ldap",
            "lightning",
            "linux",
            "matlab",
            "maven",
            "mesh01",
            "microsoft azure",
            "microsoft silverlight",
            "midp 2.0",
            "mobile",
            "mongodb",
            "msmq",
            "mysql",
            "node.js",
            "nodejs",
            "nosql",
            "objective c",
            "oracle 10g",
            "oracle 9i",
            "osx",
            "other",
            "perl",
            "phonegap",
            "photoshop",
            "php",
            "pl/sql",
            "play! framework",
            "postgresql",
            "predix",
            "python",
            "r",
            "reactjs",
            "redis",
            "remoting",
            "rest",
            "rmi",
            "ruby",
            "ruby on rails",
            "salesforce",
            "salesforce.com",
            "sap",
            "sencha touch 2",
            "servlet",
            "sfdc mobile",
            "sharepoint 3.0",
            "siebel",
            "smartsheet",
            "spark",
            "spring",
            "sql",
            "sql server",
            "sql server 2000",
            "sql server 2008",
            "ssis",
            "struts",
            "swift",
            "swing",
            "swt",
            "titanium",
            "tvos",
            "twilio",
            "twitter bootstrap",
            "uml",
            "use case diagrams (tcuml)",
            "vb",
            "vb.net",
            "vertica",
            "visualforce",
            "web application",
            "web services",
            "windows communication foundation",
            "windows server",
            "windows server 2003",
            "windows workflow foundation",
            "winforms controls",
            "word/rich text",
            "wordpress",
            "wpf",
            "xaml",
            "xcode",
            "xml",
            "xmpp",
            "xsl",
            "xul"
    };

    public static final String[] TECHNOLOGIES = {
            ".NET",
            ".NET System.Addins",
            "ADO.NET",
            "AJAX",
            "API",
            "ASP.NET",
            "ASP.NET Web Parts",
            "ActionScript",
            "Active Directory",
            "Android",
            "Angular.js",
            "Ant",
            "Apache Derby",
            "Apex",
            "Applet",
            "Backbone.js",
            "BizTalk",
            "Blackberry SDK",
            "Bootstrap",
            "C",
            "C#",
            "C++",
            "COBOL",
            "COM",
            "CSS",
            "Castor",
            "Chatter",
            "Cisco",
            "ClickOnce",
            "CoffeeScript",
            "Data Science",
            "Databasedotcom",
            "Docker",
            "Dojo",
            "Drools",
            "EJB",
            "Eclipse Plugin",
            "Elasticsearch",
            "Express",
            "Flash",
            "Flex",
            "Force.com Sites",
            "Fortran",
            "Go",
            "Google API",
            "Google App Engine",
            "Gradle",
            "Grommet",
            "Groovy",
            "HPE Haven OnDemand",
            "HTML",
            "HTML5",
            "HTTP",
            "Hibernate",
            "IBM AIX",
            "IBM COGNOS",
            "IBM Content Manager",
            "IBM DB2",
            "IBM Lotus Domino",
            "IBM Lotus Notes",
            "IBM PL/1",
            "IBM REXX",
            "IBM Rational Application Developer",
            "IBM Rational Data Architect",
            "IBM Rational Data Studio",
            "IBM Rational Software Architect",
            "IBM Rational Team Concert",
            "IBM WebSphere Application Server",
            "IBM WebSphere DataPower",
            "IBM WebSphere DataStage",
            "IBM WebSphere MQ",
            "IBM WebSphere Message Broker",
            "IBM WebSphere Portal",
            "IIS",
            "Illustrator",
            "Ionic",
            "J2EE",
            "J2ME",
            "JBoss Seam",
            "JDBC",
            "JFace",
            "JMS",
            "JPA",
            "JQuery",
            "JSF",
            "JSON",
            "JSP",
            "JUnit",
            "Jabber",
            "Java",
            "Java Application",
            "JavaBean",
            "JavaScript",
            "LDAP",
            "Lightning",
            "MIDP 2.0",
            "MSMQ",
            "Matlab",
            "Maven",
            "Microsoft SilverLight",
            "MongoDB",
            "MySQL",
            "NoSQL",
            "Node.js",
            "OSX",
            "Objective C",
            "Oracle 10g",
            "Oracle 9i",
            "Other",
            "PHP",
            "PL/SQL",
            "Perl",
            "PhoneGap",
            "Photoshop",
            "Play! Framework",
            "PostgreSQL",
            "Predix",
            "Python",
            "R",
            "REST",
            "ReactJS",
            "Redis",
            "Ruby",
            "Ruby on Rails",
            "SAP",
            "SFDC Mobile",
            "SQL",
            "SQL Server",
            "SSIS",
            "SWT",
            "Salesforce",
            "Sencha Touch 2",
            "Servlet",
            "Sharepoint 3.0",
            "Siebel",
            "Spark",
            "Spring",
            "Struts",
            "Swift",
            "Swing",
            "RMI",
            "Titanium",
            "Twitter Bootstrap",
            "UML",
            "VB",
            "VB.NET",
            "Vertica",
            "Visualforce",
            "WPF",
            "Web Application",
            "Web Services",
            "WinForms Controls",
            "Windows Communication Foundation",
            "Windows Server",
            "Windows Workflow Foundation",
            "Word/Rich Text",
            "XAML",
            "XML",
            "XMPP",
            "XSL",
            "XUL",
            "Xcode",
            "iBATIS/MyBatis",
            "iOS",
            "jQuery",
            "tvOS"};

    public static final String[]LANGUAGES={
        "Java","C","C#","C++","Python","Go","HTML","HTML5", "R","Ruby", "Perl", "PHP","JavaScript","Swift","VB","Objective C",
            "SQL","Matlab","Fortran","ActionScript"
    };

    public static final String[] PLATFORMS = {"AWS",
            "Android",
            "Beanstalk",
            "Box",
            "Brivo Labs",
            "Cisco",
            "Cloud Foundry",
            "CloudFactor",
            "DocuSign",
            "EC2",
            "Facebook",
            "FinancialForce",
            "Force.com",
            "Gaming",
            "Google",
            "HP Haven",
            "HPE Haven OnDemand",
            "HTML",
            "Heroku",
            "IBM Bluemix",
            "Linux",
            "MESH01",
            "Microsoft Azure",
            "Mobile",
            "NodeJS",
            "Predix",
            "Salesforce.com",
            "Smartsheet",
            "Twilio",
            "Wordpress",
            "iOS"};

    public static final String CLASSIFIER_DIRECTORY = "F:/arff/classifier/";
    public static final String CLUSTER_DIRECTORY = "F:/arff/cluster/";
    public static final String LOCAL_DIRECTORY = "F:/arff/local/";
}
