package com.buaa.act.sdp.common;

/**
 * Created by yang on 2016/11/24.
 */
public class Constant {

    public static final String[] TECHNOLOGIES = {
            ".NET",
            ".NET System.Addins",
            "ADO.NET",
            "AJAX",
            "API",
            "ASP.NET",
            "ASP.NET AJAX",
            "ASP.NET Web Parts",
            "ActionScript",
            "Active Directory",
            "Android",
            "Angular.js",
            "Ant",
            "Apache Derby",
            "Apex",
            "Applet",
            "Backbone.js",
            "BizTalk",
            "Blackberry SDK",
            "Bootstrap",
            "C",
            "C#",
            "C++",
            "COBOL",
            "COM",
            "COM+",
            "CSS",
            "Castor",
            "Chatter",
            "Cisco",
            "ClickOnce",
            "CoffeeScript",
            "Data Science",
            "Databasedotcom",
            "Docker",
            "Dojo",
            "Drools",
            "EJB",
            "Eclipse Plugin",
            "Elasticsearch",
            "Express",
            "Flash",
            "Flex",
            "Force.com Sites",
            "Fortran",
            "Go",
            "Google API",
            "Google App Engine",
            "Gradle",
            "Grommet",
            "Groovy",
            "HPE Haven OnDemand",
            "HTML",
            "HTML5",
            "HTTP",
            "Hibernate",
            "IBM AIX",
            "IBM COGNOS",
            "IBM Content Manager",
            "IBM DB2",
            "IBM Lotus Domino",
            "IBM Lotus Notes",
            "IBM PL/1",
            "IBM REXX",
            "IBM Rational Application Developer",
            "IBM Rational Data Architect",
            "IBM Rational Data Studio",
            "IBM Rational Software Architect",
            "IBM Rational Team Concert",
            "IBM WebSphere Application Server",
            "IBM WebSphere DataPower",
            "IBM WebSphere DataStage",
            "IBM WebSphere MQ",
            "IBM WebSphere Message Broker",
            "IBM WebSphere Portal",
            "IIS",
            "Illustrator",
            "Ionic",
            "J2EE",
            "J2ME",
            "JBoss Seam",
            "JDBC",
            "JFace",
            "JMS",
            "JPA",
            "JQuery",
            "JSF",
            "JSON",
            "JSP",
            "JUnit",
            "Jabber",
            "Java",
            "Java Application",
            "JavaBean",
            "JavaScript",
            "LDAP",
            "Lightning",
            "MIDP 2.0",
            "MSMQ",
            "Matlab",
            "Maven",
            "Microsoft SilverLight",
            "MongoDB",
            "MySQL",
            "NoSQL",
            "Node.js",
            "OSX",
            "Objective C",
            "Oracle 10g",
            "Oracle 9i",
            "Other",
            "PHP",
            "PL/SQL",
            "Perl",
            "PhoneGap",
            "Photoshop",
            "Play! Framework",
            "PostgreSQL",
            "Predix",
            "Python",
            "R",
            "REST",
            "ReactJS",
            "Redis",
            "Ruby",
            "Ruby on Rails",
            "SAP",
            "SFDC Mobile",
            "SQL",
            "SQL Server",
            "SSIS",
            "SWT",
            "Salesforce",
            "Sencha Touch 2",
            "Servlet",
            "Sharepoint 3.0",
            "Siebel",
            "Spark",
            "Spring",
            "Struts",
            "Swift",
            "Swing",
            "Titanium",
            "Twitter Bootstrap",
            "UML",
            "VB",
            "VB.NET",
            "Vertica",
            "Visualforce",
            "WPF",
            "Web Application",
            "Web Services",
            "WinForms Controls",
            "Windows Communication Foundation",
            "Windows Server",
            "Windows Workflow Foundation",
            "Word/Rich Text",
            "XAML",
            "XML",
            "XMPP",
            "XSL",
            "XUL",
            "Xcode",
            "iBATIS/MyBatis",
            "iOS",
            "iOS 5.0",
            "iOS 6.0",
            "iOS 8.0",
            "iOS 8.0",
            "jQuery",
            "jQuery Mobile",
            "tvOS"};

    public static final String[]LANGUAGES={
        "Java","C","C#","C++","Python","Go","HTML","HTML5", "R","Ruby", "Perl", "PHP","JavaScript","Swift","VB","Objective C",
            "SQL","Matlab","Fortran","ActionScript"
    };

    public static final String[] PLATFORMS = {"AWS",
            "Android",
            "Beanstalk",
            "Box",
            "Brivo Labs",
            "Cisco",
            "Cloud Foundry",
            "CloudFactor",
            "DocuSign",
            "EC2",
            "Facebook",
            "FinancialForce",
            "Force.com",
            "Gaming",
            "Google",
            "HP Haven",
            "HPE Haven OnDemand",
            "HTML",
            "Heroku",
            "IBM Bluemix",
            "Linux",
            "MESH01",
            "Microsoft Azure",
            "Mobile",
            "NodeJS",
            "Other",
            "Predix",
            "Salesforce.com",
            "Smartsheet",
            "Twilio",
            "Wordpress",
            "iOS"};

    public static final String DIRECTORY = "F:/arff/classifier/";
}
